version: '3'

service:
  api-solid-pg:
    image: bitname/postgresql
    ports:
      - 5434:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
